### ISSUE TITLE
Internal Server Error when registering Org

### ISSUE THREAD

**Issue by rdurham1007** [henry232323/sc-market#2]
I received an internal server error when trying to register my org.

https://robertsspaceindustries.com/orgs/NAJAECHO

Code is on the manifesto page.

**Comment by henry232323** [comment]
Sorry, this issue got lost. Were you able to resolve the problem? This error can occasionally occur during downtime windows caused by [this issue](https://github.com/Dymerz/RSI-Scraper/issues/6), which unfortunately we have no control over. See the linked issue for full details on the timeframe in which the error is likely to occur.
